# Generated by Django 2.1.5 on 2019-02-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190225_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.FloatField(blank=True, null=True, verbose_name='Teléfono'),
        ),
    ]
