# Generated by Django 2.1.5 on 2019-02-25 17:07

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20190225_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=registration.models.custom_upload_to, verbose_name='Foto'),
        ),
    ]
