# Generated by Django 2.1.5 on 2019-02-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20190225_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privilegio',
            field=models.CharField(choices=[('A', 'Admin'), ('U', 'Usuario'), ('M', 'Museos')], default='U', max_length=1, verbose_name='Privilegios'),
        ),
    ]
