# Generated by Django 2.1.5 on 2019-02-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_profile_privilegio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='privilegio',
        ),
    ]
