# Generated by Django 2.1.7 on 2019-03-11 15:05

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import museos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('address', models.CharField(max_length=200, verbose_name='Direccion')),
                ('opening_hour', models.TimeField(default=django.utils.timezone.now, verbose_name='Apertura')),
                ('close_hour', models.TimeField(default=django.utils.timezone.now, verbose_name='Cierra')),
                ('accesibilty', models.NullBooleanField(verbose_name='Acceso para discapacitados')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('photom', models.ImageField(blank=True, null=True, upload_to=museos.models.custom_upload_to, verbose_name='Foto')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'museo',
                'verbose_name_plural': 'museos',
                'ordering': ['order', 'title'],
            },
        ),
    ]
