# Generated by Django 2.1.7 on 2019-03-13 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import museos.models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='museo',
            options={'ordering': ['title'], 'verbose_name': 'museo', 'verbose_name_plural': 'museos'},
        ),
        migrations.RemoveField(
            model_name='museo',
            name='order',
        ),
        migrations.RemoveField(
            model_name='museo',
            name='photom',
        ),
        migrations.AddField(
            model_name='museo',
            name='coffee',
            field=models.BooleanField(default=False, verbose_name='Cafeteria'),
        ),
        migrations.AddField(
            model_name='museo',
            name='colection',
            field=models.CharField(choices=[('ARTE', 'ARTE'), ('HISTORIA', 'HISTORIA'), ('ARQUEOLOGIA', 'ARQUEOLOGIA'), ('ANTROPOLOGIA', 'ANTROPOLOGIA'), ('CIENCIA/TECNOLOGIA', 'CIENCIA/TECNOLOGIA')], default=datetime.datetime(2019, 3, 13, 17, 43, 59, 49291, tzinfo=utc), max_length=20, verbose_name='Colección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museo',
            name='district',
            field=models.CharField(choices=[('AGUADA', 'AGUADA'), ('BARRIO SUR', 'BARRIO SUR'), ('BUCEO', 'BUCEO'), ('CARRASCO', 'CARRASCO'), ('CENTRO', 'CENTRO'), ('CERRO', 'CERRO'), ('CIUDAD VIEJA', 'CIUDAD VIEJA'), ('CORDON', 'CORDON'), ('BARRIO CAPURRO', 'BARRIO CAPURRO'), ('LA UNION', 'LA UNION'), ('MARONAS', 'MARONAS'), ('PARQUE RODO', 'PARQUE RODO'), ('PENAROL', 'PENAROL'), ('POCITOS', 'POCITOS'), ('PUNTA GORDA', 'PUNTA GORDA')], default=datetime.datetime(2019, 3, 13, 17, 44, 13, 220519, tzinfo=utc), max_length=20, verbose_name='Barrio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museo',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to=museos.models.custom_upload_to, verbose_name='Foto 1'),
        ),
        migrations.AddField(
            model_name='museo',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=museos.models.custom_upload_to, verbose_name='Foto 2'),
        ),
        migrations.AddField(
            model_name='museo',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=museos.models.custom_upload_to, verbose_name='Foto 3'),
        ),
        migrations.AddField(
            model_name='museo',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name='WIFI'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='accesibilty',
            field=models.BooleanField(default=False, verbose_name=' Acceso para discapacitados'),
        ),
    ]
