# Generated by Django 2.1.5 on 2019-03-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0002_auto_20190313_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='museo',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Página Web'),
        ),
        migrations.AddField(
            model_name='museo',
            name='web',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Página Web'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='colection',
            field=models.CharField(choices=[('ARTE', 'ARTE'), ('HISTORIA', 'HISTORIA'), ('ARQUEOLOGIA', 'ARQUEOLOGIA'), ('ANTROPOLOGIA', 'ANTROPOLOGIA'), ('CIENCIA', 'CIENCIA'), ('AGRICULTURA', 'AGRICULTURA')], max_length=20, verbose_name='Colección'),
        ),
    ]
