# Generated by Django 2.1.5 on 2019-03-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0004_auto_20190314_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museo',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Página Web'),
        ),
    ]
