# Generated by Django 2.1.5 on 2019-03-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0005_auto_20190314_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='museo',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
