# Generated by Django 2.1.5 on 2019-03-15 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0009_auto_20190315_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museo',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
