# Generated by Django 2.1.7 on 2019-03-18 00:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0010_auto_20190315_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('opening_hour', models.CharField(choices=[('00:00', 'Medianoche'), ('01:00', '01:00 AM'), ('02:00', '02:00 AM'), ('03:00', '03:00 AM'), ('04:00', '04:00 AM'), ('05:00', '05:00 AM'), ('06:00', '06:00 AM'), ('07:00', '07:00 AM'), ('08:00', '08:00 AM'), ('09:00', '09:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', 'Mediodia'), ('13:00', '01:00 PM'), ('14:00', '02:00 PM'), ('15:00', '03:00 PM'), ('16:00', '04:00 PM'), ('17:00', '05:00 PM'), ('18:00', '06:00 PM'), ('19:00', '07:00 PM'), ('20:00', '08:00 PM'), ('21:00', '09:00 PM'), ('22:00', '10:00 PM'), ('23:00', '11:00 PM')], max_length=20, verbose_name='Apertura')),
                ('close_hour', models.CharField(choices=[('00:00', 'Medianoche'), ('01:00', '01:00 AM'), ('02:00', '02:00 AM'), ('03:00', '03:00 AM'), ('04:00', '04:00 AM'), ('05:00', '05:00 AM'), ('06:00', '06:00 AM'), ('07:00', '07:00 AM'), ('08:00', '08:00 AM'), ('09:00', '09:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', 'Mediodia'), ('13:00', '01:00 PM'), ('14:00', '02:00 PM'), ('15:00', '03:00 PM'), ('16:00', '04:00 PM'), ('17:00', '05:00 PM'), ('18:00', '06:00 PM'), ('19:00', '07:00 PM'), ('20:00', '08:00 PM'), ('21:00', '09:00 PM'), ('22:00', '10:00 PM'), ('23:00', '11:00 PM')], max_length=20, verbose_name='Colección')),
                ('accesibilty', models.BooleanField(default=False, verbose_name='Para personas con discapacidad')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Ediccion')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museos.Museo', verbose_name='Museo')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['order', 'title'],
            },
        ),
    ]
