# Generated by Django 2.1.7 on 2019-03-19 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('museos', '0011_actividades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='museum',
        ),
        migrations.AddField(
            model_name='actividades',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='museo',
            name='activities',
            field=models.ManyToManyField(to='museos.Actividades', verbose_name='Lista de actividades'),
        ),
    ]
