# Generated by Django 2.1.7 on 2019-03-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0013_auto_20190319_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='museo',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
