# Generated by Django 2.1.7 on 2019-03-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0014_museo_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividades',
            options={'ordering': ['title', 'content'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.RemoveField(
            model_name='actividades',
            name='order',
        ),
        migrations.AddField(
            model_name='actividades',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
