# Generated by Django 2.1.7 on 2019-03-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0016_auto_20190325_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museo',
            name='district',
            field=models.CharField(choices=[('AGUADA', 'AGUADA'), ('AIRES PUROS', 'AIRES PUROS'), ('BARRIO SUR', 'BARRIO SUR'), ('BUCEO', 'BUCEO'), ('CARRASCO', 'CARRASCO'), ('CENTRO', 'CENTRO'), ('CERRO', 'CERRO'), ('CIUDAD VIEJA', 'CIUDAD VIEJA'), ('CORDON', 'CORDON'), ('BARRIO CAPURRO', 'BARRIO CAPURRO'), ('LA UNION', 'LA UNION'), ('LEZICA', 'LEZICA'), ('MARONAS', 'MARONAS'), ('PALERMO', 'PALERMO'), ('PARQUE RODO', 'PARQUE RODO'), ('PENAROL', 'PENAROL'), ('POCITOS', 'POCITOS'), ('PUNTA GORDA', 'PUNTA GORDA'), ('PUNTA CARRETAS', 'PUNTA CARRETAS'), ('PEREZ CASTELLANOS', 'PEREZ CASTELLANOS'), ('SAYAGO', 'SAYAGO'), ('TRES CRUCES', 'TRES CRUCES')], max_length=20, verbose_name='Barrio'),
        ),
    ]
